// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FluentApiTabloOlusturmaML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public string Col2 { get; set; }


    }
}
