// This file was auto-generated by ML.NET Model Builder. 

using System;
using FluentApiTabloOlusturmaML.Model;

namespace FluentApiTabloOlusturmaML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col0 = @"başarılı bir ürün",
                Col1 = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col2 with predicted Col2 from sample data...\n\n");
            Console.WriteLine($"Col0: {sampleData.Col0}");
             Console.WriteLine($"\n\nPredicted Col2 value {predictionResult.Prediction} \nPredicted Col2 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
